#!/bin/bash

if tmux has-session -t vim
then
    if [ "$#" != "1" ]
    then
        echo "There is another VIM session in TMUX and we cannot open tabs with multiple parameters. Do manually!"
        exit 1;
    fi

    file=$(readlink -f $1)
    tmux send-keys -t vim:vim ":tabe $file" C-m
    tmux attach-session -t vim
    exit 1;
fi

tmux new-session -s vim -n vim "vim $@"
